Bkstg\TimelineBundle\Entity\Action:
    type: entity
    repositoryClass: Bkstg\TimelineBundle\Repository\ActionRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToMany:
        actionComponents:
            targetEntity: Bkstg\TimelineBundle\Entity\ActionComponent
            mappedBy: action
            cascade:
                - persist
        timelines:
            targetEntity: Bkstg\TimelineBundle\Entity\Timeline
            mappedBy: action
