Bkstg\TimelineBundle\Entity\Component:
    type: entity
    repositoryClass: Bkstg\TimelineBundle\Repository\ComponentRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
