Bkstg\TimelineBundle\Entity\Timeline:
    type: entity
    repositoryClass: Bkstg\TimelineBundle\Repository\TimelineRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        action:
            targetEntity: Bkstg\TimelineBundle\Entity\Action
            inversedBy: timelines
        subject:
            targetEntity: Bkstg\TimelineBundle\Entity\Component
            joinColumn:
                onDelete: CASCADE
