services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Bkstg\TimelineBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    # Controller services.
    Bkstg\TimelineBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    # Block services.
    Bkstg\TimelineBundle\Block\:
        resource: '../../Block'
        public: true
        arguments:
            - null
            - '@sonata.templating'
        tags:
            - { name: sonata.block }

    # Notification service alias for autowiring.
    Spy\Timeline\Driver\ActionManagerInterface: '@spy_timeline.action_manager.orm'
    Spy\Timeline\Driver\TimelineManagerInterface: '@spy_timeline.timeline_manager.orm'

    # Event listener
    Bkstg\TimelineBundle\EventListener\ProductionTimeline:
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.bkstg.timeline.production_timeline, method: onBlock }
    Bkstg\TimelineBundle\EventListener\AdminTimeline:
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.bkstg.timeline.admin_timeline, method: onBlock }
