<?php

namespace Bkstg\NotificationBundle\Repository;

/**
 * ActionComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionComponentRepository extends \Doctrine\ORM\EntityRepository
{
}
