bkstg_notification_mark_read:
    path: /{id}/read
    defaults:
        _controller: Bkstg\NotificationBundle\Controller\NotificationController:markReadAction
bkstg_notification_mark_all_read:
    path: /read-all
    defaults:
        _controller: Bkstg\NotificationBundle\Controller\NotificationController:markAllReadAction
bkstg_notification_timeline:
    path: /timeline
    defaults:
        _controller: Bkstg\NotificationBundle\Controller\NotificationController:timelineAction
